### ISSUE TITLE
deth_ctf - Salt used incorrectly in `computeAddress`

### ISSUE THREAD

**Issue by Vancelott** [Egis-Security/CTF_Challenge#42]
## Description of the Bug:

The factory contract is intended to be used by users to deploy multiple vaults, however, with the current implementation, that's not possible. This is all due to the fact that the `salt` parameter is [hardcoded](https://github.com/Egis-Security/CTF_Challenge/blob/main/deth_ctf/Factory%26Vault.sol#L21) and it doesn't allow the user to input a salt of their own. Although it's good practice to include the address of the `msg.sender` in the creation of an address when using CREATE2, it's used incorrectly in this case.

## Impact: 

Only one vault can be deployed per user, breaking one of the core functionalities of the protocol.

## Solution (Optional): 

One way to mitigate this issue, is to refactor the functions so that the `salt` is a user-inputted parameter:
```diff

contract Factory {
    error AlreadyDeployed();

-     function deployVault() external {
+    function deployVault(uint256 _salt) external {
-        address vaultAddress = computeAddress();
+       address vaultAddress = computeAddress(_salt);

        if (vaultAddress.codehash != bytes32(0)) {
            revert AlreadyDeployed();
        }

        bytes32 salt = bytes32(uint256(uint160(msg.sender)));
-       vaultAddress = address(new Vault{salt: salt}(msg.sender));
+      vaultAddress = address(new Vault{salt: bytes32(_salt)}(msg.sender));
    }

    function computeAddress(uint256 _salt) public view returns (address) {
-         bytes32 salt = bytes32(uint256(uint160(msg.sender)));
+        bytes32 msgSender = bytes32(uint256(uint160(msg.sender)));
        return address(
            uint160(
-                uint256(
-                    keccak256(abi.encodePacked(bytes1(0xff), address(this), salt, keccak256(type(Vault).creationCode)))
-                )
+               uint256(
+                    keccak256(abi.encodePacked(bytes1(0xff), msgSender, _salt, keccak256(type(Vault).creationCode)))
+               )
            )
        );
    }
}

```

**Comment by 0xdeth** [comment]
This is by design. One address should be able to create one Vault.
